trigger: none

stages:
- stage: BuildAndVersion
  pool:
    name: ITTS01
  displayName: Increment Version and Build
  jobs:
  - job: IncrementVersion
    displayName: Increment Version, Build, Commit, Pack and Push
    steps:
    - checkout: self
      persistCredentials: true

    # Step 1: Increment the version number in .nuspec and .psd1
    - task: PowerShell@2
      displayName: "Increment version in .psd1"
      inputs:
        targetType: inline
        script: |
          $nuspecPath = "$(Build.SourcesDirectory)\LDXLogging\LDXLogging.nuspec"
          $psd1Path = "$(Build.SourcesDirectory)\LDXLogging\LDXLogging.psd1"

          # Function to increment version
          function Increment-Version($version) {
              $parts = $version -split '\.'
              $parts[2] = [int]$parts[2] + 1 # Increment the patch version
              return "$($parts[0]).$($parts[1]).$($parts[2])"
          }

          # Increment version in .nuspec
          [xml]$nuspecXml = Get-Content $nuspecPath
          $currentVersion = $nuspecXml.package.metadata.version
          $newVersion = Increment-Version $currentVersion
          $nuspecXml.package.metadata.version = $newVersion
          $nuspecXml.Save($nuspecPath)
          Write-Host "Updated .nuspec version: $newVersion"
          # Increment version in .psd1
          $psd1Content = Get-Content $psd1Path
          $psd1Content = $psd1Content -replace '(?<=ModuleVersion\s*=\s*'')[^'']+', $newVersion
          Set-Content $psd1Path $psd1Content
          Write-Host "Updated .psd1 version: $newVersion"
          Write-Output "##vso[task.setvariable variable=newVersion]$newVersion"
          Write-Output "##vso[task.setvariable variable=nuspecPath]$nuspecPath"
          Write-Output "##vso[task.setvariable variable=psd1Path]$psd1Path"

    # Step 2: Commit the updated files back to the repository
    - script: |
        git config user.name "$(System.DefinitionName)"
        git config user.email "noreply@azure.com"
        git add "$(nuspecPath)"
        git add "$(psd1Path)"
        git commit -m "Incremented version to $(newVersion)"
        git push origin HEAD:$(Build.SourceBranchName)
      displayName: "Commit updated version to repository"

    - task: PowerShell@2
      displayName: 'Publish LDXLogging to PSGallery'
      inputs:
        targetType: 'inline'
        script: 'publish-Module -Path "$(Build.SourcesDirectory)\LDXLogging" -Repository PSGallery -NuGetApiKey $(GithubPAT)'
        pwsh: true