trigger: none

stages:
- stage: BuildAndVersion
  pool:
    name: ITTS01
  displayName: Increment Version and Build
  jobs:
  - job: IncrementVersion
    displayName: Increment Version, Build, Commit, Pack and Push
    steps:
    - checkout: self
      persistCredentials: true

    # Step 1: Increment the version number in .nuspec and .psd1
    - task: PowerShell@2
      displayName: "Increment version in .psd1"
      inputs:
        targetType: inline
        script: |
          $nuspecPath = "$(Build.SourcesDirectory)\LDXLogging\LDXLogging.nuspec"
          $psd1Path = "$(Build.SourcesDirectory)\LDXLogging\LDXLogging.psd1"

          # Function to increment version
          function Increment-Version($version) {
              $parts = $version -split '\.'
              $parts[2] = [int]$parts[2] + 1 # Increment the patch version
              return "$($parts[0]).$($parts[1]).$($parts[2])"
          }

          # Increment version in .nuspec
          [xml]$nuspecXml = Get-Content $nuspecPath
          $currentVersion = $nuspecXml.package.metadata.version
          $newVersion = Increment-Version $currentVersion
          $nuspecXml.package.metadata.version = $newVersion
          $nuspecXml.Save($nuspecPath)
          Write-Host "Updated .nuspec version: $newVersion"
          # Increment version in .psd1
          $psd1Content = Get-Content $psd1Path
          $psd1Content = $psd1Content -replace '(?<=ModuleVersion\s*=\s*'')[^'']+', $newVersion
          Set-Content $psd1Path $psd1Content
          Write-Host "Updated .psd1 version: $newVersion"
          Write-Output "##vso[task.setvariable variable=newVersion]$newVersion"
          Write-Output "##vso[task.setvariable variable=nuspecPath]$nuspecPath"
          Write-Output "##vso[task.setvariable variable=psd1Path]$psd1Path"

          # Output the new version for use in subsequent steps
          Write-Output "##vso[task.setvariable variable=newVersion]$newVersion"
          Write-Output "##vso[task.setvariable variable=nuspecPath]$nuspecPath"
          Write-Output "##vso[task.setvariable variable=psd1Path]$psd1Path"

    # Step 2: Commit the updated files back to the repository
    - script: |
        git config user.name "$(System.DefinitionName)"
        git config user.email "noreply@azure.com"
        git add "$(nuspecPath)"
        git add "$(psd1Path)"
        git commit -m "Incremented version to $(newVersion)"
        git push origin HEAD:$(Build.SourceBranchName)
      displayName: "Commit updated version to repository"
      
    - task: NuGetCommand@2
      displayName: "Pack NuGet package"
      inputs:
        command: 'pack'
        packagesToPack: '$(nuspecPath)'
        versioningScheme: 'off'
    - task: NuGetCommand@2
      displayName: 'NuGet Add Source'
      inputs:
        command: custom
        arguments: 'sources Add -Name "PSGallery" -Source "https://pkgs.dev.azure.com/Lindex/54d6313b-d328-4646-9f0e-8b8d5b9aa9ae/_packaging/LdxPoshFeed/nuget/v3/index.json" -username "LDXModules" -password $(GithubPAT) -ConfigFile $(Build.SourcesDirectory)\nuget.config'

    - task: NuGetCommand@2
      displayName: 'NuGet Push'
      inputs:
        command: custom
        arguments: 'push $(Build.ArtifactStagingDirectory)\*.nupkg -Source PSGallery -apikey az -ConfigFile $(Build.SourcesDirectory)\nuget.config -Verbosity Detailed'

